int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void times_table(void);
void print_times_table(int n);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
